HTTP_PORT: 14081

STAFF_SERVICE_HOST: staff-service
STAFF_SERVICE_PORT: 14082

MYSQL:
  HOST: 34.105.93.68
  PORT: 3306
  USERNAME: root
  PASSWORD: 'admin-bpel'
  DATABASE: warehouse_service