version: "3.7"

services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.2
#    container_name: zookeeper
#    networks:
#      - store-bpel
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#
#  broker:
#    image: confluentinc/cp-kafka:7.3.2
#    container_name: kafka
#    hostname: kafka
#    networks:
#      - store-bpel
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  admin-bff:
    image: huuthotn01/admin-bff:20230513024209
    container_name: admin-bff
    hostname: admin-bff
    networks:
      - store-bpel
    volumes:
      - ./admin-bff/config.yaml:/app/bff/admin-bff/config.yaml
    ports:
      - "10000:10000"

  customer-bff:
    image: huuthotn01/customer-bff:20230513032905
    container_name: customer-bff
    hostname: customer-bff
    networks:
      - store-bpel
    volumes:
      - ./customer-bff/config.yaml:/app/bff/customer-bff/config.yaml
    ports:
      - "20000:20000"

  shared-bff:
    image: huuthotn01/shared-bff:20230513033132
    container_name: shared-bff
    hostname: shared-bff
    networks:
      - store-bpel
    volumes:
      - ./shared-bff/config.yaml:/app/bff/shared-bff/config.yaml
    ports:
      - "30000:30000"

  account-service:
    image: huuthotn01/account-service:20230513042529
    container_name: account-service
    hostname: account-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./account-service/config.yaml:/app/account-service/config.yaml
    ports:
      - "14083:14083"

#  account-service-db-migration:
#    image: huuthotn01/account-service-db-migration:20230513034025
#    container_name: account-service-db-migration
#    hostname: account-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  branch-service:
    image: huuthotn01/branch-service:20230513175356
    container_name: branch-service
    hostname: branch-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./branch-service/config.yaml:/app/branch-service/config.yaml
    ports:
      - "14000:14000"

#  branch-service-db-migration:
#    image: huuthotn01/branch-service-db-migration:20230513034147
#    container_name: branch-service-db-migration
#    hostname: branch-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  cart-service:
    image: huuthotn01/cart-service:20230513180039
    container_name: cart-service
    hostname: cart-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./cart-service/config.yaml:/app/cart-service/config.yaml
    ports:
      - "14061:14061"

#  cart-service-db-migration:
#    image: huuthotn01/cart-service-db-migration:20230513034301
#    container_name: cart-service-db-migration
#    hostname: cart-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  customer-service:
    image: huuthotn01/customer-service:20230513180330
    container_name: customer-service
    hostname: customer-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./customer-service/config.yaml:/app/customer-service/config.yaml
    ports:
      - "14050:14050"

#  customer-service-db-migration:
#    image: huuthotn01/customer-service-db-migration:20230513034409
#    container_name: customer-service-db-migration
#    hostname: customer-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  event-service:
    image: huuthotn01/event-service:20230513180511
    container_name: event-service
    hostname: event-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./event-service/config.yaml:/app/event-service/config.yaml
    ports:
      - "14060:14060"

#  event-service-db-migration:
#    image: huuthotn01/event-service-db-migration:20230513042134
#    container_name: event-service-db-migration
#    hostname: event-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  goods-service:
    image: huuthotn01/goods-service:20230513180746
    container_name: goods-service
    hostname: goods-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./goods-service/config.yaml:/app/goods-service/config.yaml
    ports:
      - "14080:14080"

#  goods-service-db-migration:
#    image: huuthotn01/goods-service-db-migration:20230513034635
#    container_name: goods-service-db-migration
#    hostname: goods-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  order-service:
    image: huuthotn01/order-service:20230513181004
    container_name: order-service
    hostname: order-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./order-service/config.yaml:/app/order-service/config.yaml
    ports:
      - "14070:14070"

#  order-service-db-migration:
#    image: huuthotn01/order-service-db-migration:20230513034529
#    container_name: order-service-db-migration
#    hostname: order-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  staff-service:
    image: huuthotn01/staff-service:20230513181216
    container_name: staff-service
    hostname: staff-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./staff-service/config.yaml:/app/staff-service/config.yaml
    ports:
      - "14082:14082"

#  staff-service-db-migration:
#    image: huuthotn01/staff-service-db-migration:20230513034746
#    container_name: staff-service-db-migration
#    hostname: staff-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  statistic-service:
    image: huuthotn01/statistic-service:20230513181359
    container_name: statistic-service
    hostname: statistic-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./statistic-service/config.yaml:/app/statistic-service/config.yaml
    ports:
      - "14090:14090"

#  statistic-service-db-migration:
#    image: huuthotn01/statistic-service-db-migration:20230513034904
#    container_name: statistic-service-db-migration
#    hostname: statistic-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

  warehouse-service:
    image: huuthotn01/warehouse-service:20230513181545
    container_name: warehouse-service
    hostname: warehouse-service
    restart: on-failure
    networks:
      - store-bpel
    volumes:
      - ./warehouse-service/config.yaml:/app/warehouse-service/config.yaml
    ports:
      - "14081:14081"

#  warehouse-service-db-migration:
#    image: huuthotn01/warehouse-service-db-migration:20230513035016
#    container_name: warehouse-service-db-migration
#    hostname: warehouse-service-db-migration
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - store-bpel

networks:
  store-bpel:
    name: store-bpel
    driver: bridge
