HTTP_PORT: 20000

CUSTOMER_SERVICE_HOST: customer-service
CUSTOMER_SERVICE_PORT: 14050
ORDER_SERVICE_HOST: order-service
ORDER_SERVICE_PORT: 14070
CART_SERVICE_HOST: cart-service
CART_SERVICE_PORT: 14061
ACCOUNT_SERVICE_HOST: account-service
ACCOUNT_SERVICE_PORT: 14083