HTTP_PORT: 14080

WAREHOUSE_SERVICE_HOST: warehouse-service
WAREHOUSE_SERVICE_PORT: 14081
EVENT_SERVICE_HOST: event-service
EVENT_SERVICE_PORT: 14060
ORDER_SERVICE_HOST: order-service
ORDER_SERVICE_PORT: 14070

MYSQL:
  HOST: mysql
  PORT: 3306
  USERNAME: bpel
  PASSWORD: 'bpel'
  DATABASE: goods_service