HTTP_PORT: 30000

GOODS_SERVICE_HOST: goods-service
GOODS_SERVICE_PORT: 14080
EVENT_SERVICE_HOST: event-service
EVENT_SERVICE_PORT: 14060
ACCOUNT_SERVICE_HOST: account-service
ACCOUNT_SERVICE_PORT: 14083
ORDER_SERVICE_HOST: order-service
ORDER_SERVICE_PORT: 14070