HTTP_PORT: 14070

GOODS_SERVICE_HOST: goods-service
GOODS_SERVICE_PORT: 14080
KAFKA_HOST: broker
KAFKA_PORT: 29092

MYSQL:
  HOST: order-service.c1wzjnxoqy5g.ap-southeast-1.rds.amazonaws.com
  PORT: 3306
  USERNAME: admin
  PASSWORD: 'admin-bpel'
  DATABASE: order_service