HTTP_PORT: 10000

BRANCH_SERVICE_HOST: branch-service
BRANCH_SERVICE_PORT: 14000
ACCOUNT_SERVICE_HOST: account-service
ACCOUNT_SERVICE_PORT: 14083
STAFF_SERVICE_HOST: staff-service
STAFF_SERVICE_PORT: 14082
GOODS_SERVICE_HOST: goods-service
GOODS_SERVICE_PORT: 14080
EVENT_SERVICE_HOST: event-service
EVENT_SERVICE_PORT: 14060
WAREHOUSE_SERVICE_HOST: warehouse-service
WAREHOUSE_SERVICE_PORT: 14081
ORDER_SERVICE_HOST: order-service
ORDER_SERVICE_PORT: 14070