HTTP_PORT: 14082

ACCOUNT_SERVICE_HOST: account-service
ACCOUNT_SERVICE_PORT: 14083
KAFKA_HOST: broker
KAFKA_PORT: 29092

MYSQL:
  HOST: 34.105.93.68
  PORT: 3306
  USERNAME: root
  PASSWORD: 'admin-bpel'
  DATABASE: staff_service