HTTP_PORT: 14082

ACCOUNT_SERVICE_HOST: account-service
ACCOUNT_SERVICE_PORT: 14083
KAFKA_HOST: broker
KAFKA_PORT: 29092

MYSQL:
  HOST: staff-service.c1wzjnxoqy5g.ap-southeast-1.rds.amazonaws.com
  PORT: 3306
  USERNAME: admin
  PASSWORD: 'admin-bpel'
  DATABASE: staff_service