HTTP_PORT: 14083

STAFF_SERVICE_HOST: staff-service
STAFF_SERVICE_PORT: 14082
CUSTOMER_SERVICE_HOST: customer-service
CUSTOMER_SERVICE_PORT: 14050
KAFKA_HOST: broker
KAFKA_PORT: 29092

MYSQL:
  HOST: 34.105.93.68
  PORT: 3306
  USERNAME: root
  PASSWORD: 'admin-bpel'
  DATABASE: account_service

SERVICE_FLAGS:
  IS_ENABLE_ASYNC: true
