HTTP_PORT: 14050

KAFKA_HOST: broker
KAFKA_PORT: 29092

MYSQL:
  HOST: customer-service.c1wzjnxoqy5g.ap-southeast-1.rds.amazonaws.com
  PORT: 3306
  USERNAME: admin
  PASSWORD: 'admin-bpel'
  DATABASE: customer_service